import React, { createContext, useContext, useState } from 'react';

const translations = {
    en: {
        // Header
        appName: 'Rural Telemedicine',
        dashboard: 'Dashboard',
        logout: 'Logout',
        login: 'Login',
        signUp: 'Sign Up',
        hello: 'Hello',

        // Landing
        heroTitle: 'Healthcare for Every Village',
        heroSubtitle: 'Connect with qualified doctors from the comfort of your home. No travel needed.',
        getStarted: 'Get Started Free',
        features: 'Features',
        easyToUse: 'Easy to Use',
        easyToUseDesc: 'Simple interface designed for everyone, including first-time smartphone users.',
        videoConsultation: 'Video Consultation',
        videoConsultationDesc: 'Talk to doctors face-to-face through video calls. Works even on slow internet.',
        digitalPrescription: 'Digital Prescriptions',
        digitalPrescriptionDesc: 'Receive prescriptions digitally. Show at any pharmacy to get your medicines.',
        howItWorks: 'How It Works',
        step1: 'Sign Up',
        step1Desc: 'Create your free account as a patient',
        step2: 'Find Doctor',
        step2Desc: 'Browse doctors and their specialties',
        step3: 'Book & Consult',
        step3Desc: 'Pick a time slot and join the video call',
        step4: 'Get Prescription',
        step4Desc: 'Receive your digital prescription instantly',
        builtForRural: 'Built for Rural India',
        free: 'Free',
        noPlatformFees: 'No Platform Fees',
        secure: 'Secure',
        privateEncrypted: 'Private & Encrypted',
        simple: 'Simple',
        minimalSteps: 'Minimal Steps',
        available247: '24/7',
        accessAnytime: 'Access Anytime',

        // Patient Dashboard
        welcome: 'Welcome',
        yourHealth: 'Your health, our priority. Book consultations with trusted doctors.',
        upcoming: 'Upcoming',
        completed: 'Completed',
        emergencyHelpline: 'Emergency Helpline',
        emergencyDesc: 'For medical emergencies, call immediately',
        ambulance: 'Ambulance: 108',
        emergency: 'Emergency: 112',
        findDoctors: 'Find Doctors',
        myAppointments: 'My Appointments',
        medicalHistory: 'Medical History',
        healthTips: 'Health Tips',
        myProfile: 'My Profile',
        searchDoctor: 'Search doctor by name...',
        allSpecialties: 'All Specialties',
        noDoctorsFound: 'No doctors found',
        scheduleConsultation: 'Schedule Consultation',
        selectTime: 'Time',
        describeSymptoms: 'Describe your symptoms (optional)',
        bookAppointment: 'Book Appointment',
        scheduled: 'Scheduled',
        joinCall: 'Join Call',
        cancel: 'Cancel',
        viewPrescription: 'View Prescription',
        rateDoctor: 'Rate Doctor',
        rated: 'Rated',
        noAppointments: 'No appointments yet',
        bookFirstConsultation: 'Book your first consultation with a doctor!',
        noHistory: 'No consultation history yet.',
        cancelled: 'Cancelled',
        downloadPdf: 'Download PDF',
        close: 'Close',
        submitRating: 'Submit Rating',
        writeReview: 'Write a short review (optional)...',
        thanksFeedback: 'Thank you for your feedback!',
        yearsExp: 'years experience',
        reviews: 'reviews',
        symptoms: 'Symptoms',

        // Health Tips
        stayHydrated: 'Stay Hydrated',
        stayHydratedDesc: 'Drink 8-10 glasses of water daily, especially in hot weather.',
        washHands: 'Wash Hands',
        washHandsDesc: 'Wash your hands regularly with soap and water for at least 20 seconds.',
        eatFresh: 'Eat Fresh Vegetables',
        eatFreshDesc: 'Include green vegetables and seasonal fruits in your daily diet.',
        stayActive: 'Stay Active',
        stayActiveDesc: 'Walk for at least 30 minutes daily to keep your body fit.',
        sleepWell: 'Sleep Well',
        sleepWellDesc: 'Get 7-8 hours of quality sleep every night for good health.',
        preventMosquito: 'Prevent Mosquito Bites',
        preventMosquitoDesc: 'Use mosquito nets and avoid stagnant water to prevent dengue & malaria.',

        // Profile
        patientProfile: 'Patient Profile',
        age: 'Age',
        gender: 'Gender',
        bloodGroup: 'Blood Group',
        weight: 'Weight (kg)',
        height: 'Height (cm)',
        allergies: 'Known Allergies',
        chronicConditions: 'Chronic Conditions',
        emergencyContact: 'Emergency Contact',
        saveProfile: 'Save Profile',
        profileSaved: 'Profile saved successfully!',
        male: 'Male',
        female: 'Female',
        other: 'Other',

        // Doctor Dashboard
        doctorDashboard: 'Doctor Dashboard',
        upcomingAppointments: 'Upcoming Appointments',
        completedConsultations: 'Completed Consultations',
        myReviews: 'My Reviews',
        patient: 'Patient',
        dateTime: 'Date / Time',
        actions: 'Actions',
        prescribe: 'Prescribe',
        addMedicine: '+ Add Medicine',
        medicine: 'Medicine',
        dosage: 'Dosage',
        frequency: 'Frequency',
        doctorsNotes: "Doctor's Notes",
        submitComplete: 'Submit & Complete',
        noUpcoming: 'No upcoming appointments.',
        noCompleted: 'No completed consultations yet.',
        noReviews: 'No reviews yet.',
        rating: 'Rating',
        basedOn: 'Based on',
        patientReview: 'patient review',
        patientReviews: 'patient reviews',
        remove: 'Remove',

        // Prescription
        medicalPrescription: 'Medical Prescription',
        prescribedMedications: 'Prescribed Medications',

        // Auth
        createAccount: 'Create Account',
        welcomeBack: 'Welcome Back',
        name: 'Name',
        email: 'Email',
        password: 'Password',
        registerAs: 'I am registering as a:',
        patientSeekingCare: 'Patient (Seeking Care)',
        doctorProvidingCare: 'Doctor (Providing Care)',
        doctorDetails: 'Doctor Details',
        specialty: 'Specialty',
        experienceYears: 'Experience (Years)',
        registering: 'Registering...',
        loggingIn: 'Logging in...',
        alreadyHaveAccount: 'Already have an account?',
        dontHaveAccount: "Don't have an account?",
        logIn: 'Log in',

        // Notifications
        notifications: 'Notifications',
        noNotifications: 'No notifications',
        markAllRead: 'Mark all read',

        // Language
        language: 'Language',
        switchLang: 'हिंदी',
    },
    hi: {
        appName: 'ग्रामीण टेलीमेडिसिन',
        dashboard: 'डैशबोर्ड',
        logout: 'लॉग आउट',
        login: 'लॉग इन',
        signUp: 'साइन अप',
        hello: 'नमस्ते',

        heroTitle: 'हर गाँव के लिए स्वास्थ्य सेवा',
        heroSubtitle: 'अपने घर से ही योग्य डॉक्टरों से जुड़ें। कहीं जाने की ज़रूरत नहीं।',
        getStarted: 'मुफ्त शुरू करें',
        features: 'विशेषताएँ',
        easyToUse: 'उपयोग में आसान',
        easyToUseDesc: 'सभी के लिए बनाया गया सरल इंटरफ़ेस, पहली बार स्मार्टफोन उपयोगकर्ताओं के लिए भी।',
        videoConsultation: 'वीडियो परामर्श',
        videoConsultationDesc: 'वीडियो कॉल के माध्यम से डॉक्टरों से आमने-सामने बात करें।',
        digitalPrescription: 'डिजिटल नुस्खा',
        digitalPrescriptionDesc: 'डिजिटल रूप से नुस्खा प्राप्त करें। किसी भी दवाखाने में दिखाएँ।',
        howItWorks: 'कैसे काम करता है',
        step1: 'साइन अप',
        step1Desc: 'मरीज के रूप में अपना मुफ्त खाता बनाएँ',
        step2: 'डॉक्टर खोजें',
        step2Desc: 'डॉक्टरों और उनकी विशेषताओं को देखें',
        step3: 'बुक करें और परामर्श लें',
        step3Desc: 'समय चुनें और वीडियो कॉल से जुड़ें',
        step4: 'नुस्खा पाएँ',
        step4Desc: 'तुरंत अपना डिजिटल नुस्खा प्राप्त करें',
        builtForRural: 'ग्रामीण भारत के लिए बनाया गया',
        free: 'मुफ्त',
        noPlatformFees: 'कोई शुल्क नहीं',
        secure: 'सुरक्षित',
        privateEncrypted: 'निजी और एन्क्रिप्टेड',
        simple: 'सरल',
        minimalSteps: 'कम से कम कदम',
        available247: '24/7',
        accessAnytime: 'कभी भी उपलब्ध',

        welcome: 'स्वागत है',
        yourHealth: 'आपका स्वास्थ्य, हमारी प्राथमिकता। विश्वसनीय डॉक्टरों से परामर्श बुक करें।',
        upcoming: 'आगामी',
        completed: 'पूर्ण',
        emergencyHelpline: 'आपातकालीन हेल्पलाइन',
        emergencyDesc: 'चिकित्सा आपातकाल के लिए तुरंत कॉल करें',
        ambulance: 'एम्बुलेंस: 108',
        emergency: 'आपातकाल: 112',
        findDoctors: '🩺 डॉक्टर खोजें',
        myAppointments: '📅 मेरी अपॉइंटमेंट',
        medicalHistory: '📋 चिकित्सा इतिहास',
        healthTips: '💡 स्वास्थ्य सुझाव',
        myProfile: '👤 मेरी प्रोफाइल',
        searchDoctor: 'डॉक्टर का नाम खोजें...',
        allSpecialties: 'सभी विशेषताएँ',
        noDoctorsFound: 'कोई डॉक्टर नहीं मिला',
        scheduleConsultation: 'परामर्श शेड्यूल करें',
        selectTime: 'समय',
        describeSymptoms: 'अपने लक्षण बताएँ (वैकल्पिक)',
        bookAppointment: 'अपॉइंटमेंट बुक करें',
        scheduled: 'निर्धारित',
        joinCall: 'कॉल जॉइन करें',
        cancel: 'रद्द करें',
        viewPrescription: 'नुस्खा देखें',
        rateDoctor: 'डॉक्टर को रेट करें',
        rated: 'रेटेड',
        noAppointments: 'अभी तक कोई अपॉइंटमेंट नहीं',
        bookFirstConsultation: 'ऊपर डॉक्टर खोजें और अपना पहला परामर्श बुक करें!',
        noHistory: 'अभी तक कोई परामर्श इतिहास नहीं।',
        cancelled: 'रद्द',
        downloadPdf: 'PDF डाउनलोड',
        close: 'बंद करें',
        submitRating: 'रेटिंग सबमिट करें',
        writeReview: 'एक छोटी समीक्षा लिखें (वैकल्पिक)...',
        thanksFeedback: 'आपकी प्रतिक्रिया के लिए धन्यवाद!',
        yearsExp: 'वर्ष अनुभव',
        reviews: 'समीक्षाएँ',
        symptoms: 'लक्षण',

        stayHydrated: 'हाइड्रेटेड रहें',
        stayHydratedDesc: 'रोजाना 8-10 गिलास पानी पिएं, खासकर गर्मी में।',
        washHands: 'हाथ धोएं',
        washHandsDesc: 'साबुन और पानी से कम से कम 20 सेकंड तक हाथ धोएं।',
        eatFresh: 'ताज़ी सब्जियाँ खाएँ',
        eatFreshDesc: 'अपने दैनिक आहार में हरी सब्जियाँ और मौसमी फल शामिल करें।',
        stayActive: 'सक्रिय रहें',
        stayActiveDesc: 'शरीर को स्वस्थ रखने के लिए रोजाना कम से कम 30 मिनट पैदल चलें।',
        sleepWell: 'अच्छी नींद लें',
        sleepWellDesc: 'अच्छे स्वास्थ्य के लिए हर रात 7-8 घंटे की नींद लें।',
        preventMosquito: 'मच्छरों से बचें',
        preventMosquitoDesc: 'डेंगू और मलेरिया से बचने के लिए मच्छरदानी का उपयोग करें।',

        patientProfile: 'मरीज़ प्रोफाइल',
        age: 'उम्र',
        gender: 'लिंग',
        bloodGroup: 'रक्त समूह',
        weight: 'वज़न (किलो)',
        height: 'ऊँचाई (सेमी)',
        allergies: 'ज्ञात एलर्जी',
        chronicConditions: 'पुरानी बीमारियाँ',
        emergencyContact: 'आपातकालीन संपर्क',
        saveProfile: 'प्रोफाइल सेव करें',
        profileSaved: 'प्रोफाइल सफलतापूर्वक सेव हो गई!',
        male: 'पुरुष',
        female: 'महिला',
        other: 'अन्य',

        doctorDashboard: 'डॉक्टर डैशबोर्ड',
        upcomingAppointments: 'आगामी अपॉइंटमेंट',
        completedConsultations: 'पूर्ण परामर्श',
        myReviews: 'मेरी समीक्षाएँ',
        patient: 'मरीज़',
        dateTime: 'दिनांक / समय',
        actions: 'कार्रवाई',
        prescribe: 'नुस्खा लिखें',
        addMedicine: '+ दवा जोड़ें',
        medicine: 'दवा',
        dosage: 'खुराक',
        frequency: 'कितनी बार',
        doctorsNotes: 'डॉक्टर के नोट्स',
        submitComplete: 'सबमिट करें और पूरा करें',
        noUpcoming: 'कोई आगामी अपॉइंटमेंट नहीं।',
        noCompleted: 'अभी तक कोई पूर्ण परामर्श नहीं।',
        noReviews: 'अभी तक कोई समीक्षा नहीं।',
        rating: 'रेटिंग',
        basedOn: 'आधारित',
        patientReview: 'मरीज़ समीक्षा',
        patientReviews: 'मरीज़ समीक्षाएँ',
        remove: 'हटाएँ',

        medicalPrescription: 'चिकित्सा नुस्खा',
        prescribedMedications: 'निर्धारित दवाइयाँ',

        createAccount: 'खाता बनाएँ',
        welcomeBack: 'वापस आएँ',
        name: 'नाम',
        email: 'ईमेल',
        password: 'पासवर्ड',
        registerAs: 'मैं के रूप में रजिस्टर कर रहा हूँ:',
        patientSeekingCare: 'मरीज़ (देखभाल चाहने वाला)',
        doctorProvidingCare: 'डॉक्टर (देखभाल प्रदान करने वाला)',
        doctorDetails: 'डॉक्टर विवरण',
        specialty: 'विशेषता',
        experienceYears: 'अनुभव (वर्ष)',
        registering: 'रजिस्टर हो रहा है...',
        loggingIn: 'लॉग इन हो रहा है...',
        alreadyHaveAccount: 'पहले से खाता है?',
        dontHaveAccount: 'खाता नहीं है?',
        logIn: 'लॉग इन',

        notifications: 'सूचनाएँ',
        noNotifications: 'कोई सूचना नहीं',
        markAllRead: 'सभी पढ़ें',

        language: 'भाषा',
        switchLang: 'English',
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState(localStorage.getItem('lang') || 'en');

    const toggleLanguage = () => {
        const newLang = lang === 'en' ? 'hi' : 'en';
        setLang(newLang);
        localStorage.setItem('lang', newLang);
    };

    const t = (key) => translations[lang]?.[key] || translations.en[key] || key;

    return (
        <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
